1st draft for table10, 11, 12
pharmaverse/falcon pull request #102
Opened 2023-07-18 00:42 UTC by YoshitoKoujin

fda-table_10
fda-table_11
fda-table_12

2023-08-03 23:55 UTC, edelarua commented
Hi @YoshitoKoujin,

It looks great so far! I think all the logic is correct - the only thing I changed is the criteria for "AE leading to discontinuation", from `AEACN == "DRUG WITHDRAWN"` to `DCSREAS == "ADVERSE EVENT"`, but I'm not 100% sure this is correct so if you disagree with that you can change it. I also modified the data in the examples to improve them a bit.

Could you please add tests and create templates to add to the site for each table?

Thanks!

2023-08-08 19:19 UTC, edelarua requested changes
Hi @YoshitoKoujin, the templates look good, just a few formatting suggestions from me below. Thanks!

2023-08-08 19:19 UTC, edelarua commented on quarto/table-templates/template-table_10.qmd
> +# Pre-Processing - Ensure required variables FMQ01SC and FMQ01NAM exist in adae
```suggestion
# Pre-Processing - Ensure required variables fmqsc_var and fmqnam_var exist in adae
```

2023-08-08 19:19 UTC, edelarua commented on quarto/table-templates/template-table_10.qmd
> +| `fmq_scope`      | (`character`) FMQ scope, must be "NARROW" or "BROAD".
```suggestion
| `fmq_scope`      | (`character`) FMQ scope, can be `"NARROW"` or `"BROAD"`.                                                                                                                                                                                                  | `"NARROW"`    |
```

2023-08-08 19:19 UTC, edelarua commented on quarto/table-templates/template-table_10.qmd
> +| `na_level`       | (`character`) string to represent missing values.
```suggestion
| `na_level`       | (`character`) String to represent missing values.                                                                                                                                                                                                      | `"<Missing>"` |
```

2023-08-08 19:19 UTC, edelarua commented on quarto/table-templates/template-table_11.qmd
> +# Pre-Processing - Ensure required variables FMQ01SC and FMQ01NAM exist in adae
```suggestion
# Pre-Processing - Ensure required variables fmqsc_var and fmqnam_var exist in adae
```

2023-08-08 19:19 UTC, edelarua commented on quarto/table-templates/template-table_11.qmd
> +| `fmq_scope`      | (`character`) FMQ scope, must be "NARROW" or "BROAD".
```suggestion
| `fmq_scope`      | (`character`) FMQ scope, can be `"NARROW"` or `"BROAD"`.                                                                                                                                                                                               | `"NARROW"`    |
```

2023-08-08 19:19 UTC, edelarua commented on quarto/table-templates/template-table_11.qmd
> +| `na_level`       | (`character`) string to represent missing values.
```suggestion
| `na_level`       | (`character`) String to represent missing values.                                                                                                                                                                                                      | `"<Missing>"` |
```

2023-08-08 19:19 UTC, edelarua commented on quarto/table-templates/template-table_12.qmd
> +library(dplyr)
Not used in this example so we can exclude it

```suggestion
```

2023-08-08 19:19 UTC, edelarua commented on quarto/table-templates/template-table_12.qmd
> +-   **`adae`**: `SAFFL`, `USUBJID`, `AESOC`, `DCSREAS` and the variables specified by `pref_var` and `arm_var`.
```suggestion
-   **`adae`**: `SAFFL`, `USUBJID`, `AEBODSYS`, `DCSREAS` and the variables specified by `pref_var` and `arm_var`.
```

2023-08-09 01:04 UTC, YoshitoKoujin commented
> Hi @YoshitoKoujin, the templates look good, just a few formatting suggestions from me below. Thanks!

Hi @edelarua, Thank you for your review! I have updated the files. If no more update is required please let me know. I would like to merge to main. Thank you!

2023-08-09 01:38 UTC, edelarua approved these changes
Good to go - thanks @YoshitoKoujin!

2023-08-09 02:38 UTC, merged