66 table 5
pharmaverse/falcon pull request #70
Opened 2023-06-13 13:02 UTC by aassuied-ps

Closes #66

2023-06-14 13:08 UTC, jknizia requested changes
Hi Alex, 
thanks for the request. I have only one minor comment - other than that it looks very good to me.

2023-06-14 13:08 UTC, jknizia commented on quarto/table-templates/template-table_05.qmd
> +------------------------------------------------------------------------
I'd suggest to remove the second horizontal line since it is inconsistant with the other template sites.

2023-06-14 13:08 UTC, jknizia commented on quarto/table-templates/template-table_05.qmd
> +------------------------------------------------------------------------
Okay, now that I compare the sites, I recognize that this shouldn't be removed, but moved to line 44 to seperate the "Required variables" list and the table :-)

2023-06-14 13:34 UTC, aassuied-ps commented on quarto/table-templates/template-table_05.qmd
> +------------------------------------------------------------------------
Indeed it's working by just deleting one of the horizontal lines and I get the same result as table 6 (horizontal line just above  the table header), is it what you're talking about? I don't see a difference in the code that could explain why table 2 does not have it though...

2023-06-15 06:46 UTC, jknizia approved these changes
Thanks Alex, looks good now!

2023-06-15 07:07 UTC, merged